apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-production
  namespace: mlops-system
spec:
  project: default
  source:
    repoURL: https://github.com/rubannn/goit-MLOps-fp.git
    targetRevision: main
    path: gitops/inference-production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
