apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: mlops-system
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: minio
    targetRevision: 17.0.21
    helm:
      values: |
        image:
          repository: bitnamilegacy/minio
        auth:
          rootUser: minioadmin
          rootPassword: minioadmin123
        defaultBuckets: "mlflow-artifacts"
        service:
          type: ClusterIP
        console:
          enabled: false
        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
