apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlops-engineer-full
  namespace: staging
rules:
  - apiGroups: ["", "apps", "batch", "monitoring.coreos.com"]
    resources: ["*"]
    verbs: ["*"]
